// src/components/data/SoftwareBuildChanges.tsx
import type { ReactElement } from "react";
import { Fragment } from "react";

import { getProjectRepository } from "@/lib/service/github";
import type { Build } from "@/lib/service/types";
import styles from "@/styles/components/data/SoftwareBuildChanges.module.css";

export interface SoftwareBuildChangesProps {
  project: string;
  build: Build;
  version: string;
}

const SoftwareBuildChanges = ({ project, build, version }: SoftwareBuildChangesProps) => (
  <>
    {build.commits.map((change) => {
      const [firstLine, ...restLines] = change.message.split(/\r?\n/);
      const hasAdditionalContent = restLines.length > 0;
      const fullMessage = hasAdditionalContent ? change.message : undefined;

      return (
        <p key={change.sha} className={styles.commitMessage}>
          <a
            href={`${getProjectRepository(project, version)}/commit/${change.sha}`}
            className={styles.commit}
            rel="noreferrer"
            target="_blank"
          >
            {change.sha.slice(0, 7)}
          </a>
          <span title={fullMessage}>{formatCommitMessage(firstLine, project, styles.issue)}</span>
        </p>
      );
    })}
    {build.commits.length === 0 && <i className="text-gray-600">No changes</i>}
  </>
);

export default SoftwareBuildChanges;

const formatCommitMessage = (summary: string, project: string, highlightClass: string): ReactElement[] => {
  // Regex for issues (#123) and commit links
  const regex = /(@?https:\/\/github\.com\/[\w-]+\/[\w-]+\/commit\/([a-f0-9]{7,40}))|([^&])(#[0-9]+)/gim;
  let key = 0;
  const trimmedSummary = summary.replace(/[\r\n]+$/g, "");
  const elements: ReactElement[] = [];
  let lastIndex = 0;
  let match;
  while ((match = regex.exec(trimmedSummary)) !== null) {
    if (match.index > lastIndex) {
      elements.push(<Fragment key={key++}>{trimmedSummary.slice(lastIndex, match.index)}</Fragment>);
    }
    if (match[2]) {
      // Commit link
      const url = match[1].replace(/^@/, "");
      const shortHash = match[2].slice(0, 7);
      elements.push(
        <a key={key++} className={highlightClass} href={url} target="_blank" rel="noreferrer">
          {shortHash}
        </a>,
      );
    } else if (match[4]) {
      elements.push(
        <Fragment key={key++}>{match[3]}</Fragment>,
        <a
          key={key++}
          className={highlightClass}
          href={`https://github.com/PaperMC/${project}/issues/${match[4].slice(1)}`}
          target="_blank"
          rel="noreferrer"
        >
          {match[4]}
        </a>,
      );
    }
    lastIndex = regex.lastIndex;
  }
  if (lastIndex < trimmedSummary.length) {
    elements.push(<Fragment key={key++}>{trimmedSummary.slice(lastIndex)}</Fragment>);
  }
  return elements;
};

// src/components/data/SoftwareBuildChanges.svelte
<script lang="ts">
  import type { Build } from '@/utils/types';
  import { getProjectRepository } from '@/utils/github';

  interface Props {
    project: string;
    build: Build;
    version: string;
  }

  let { project, build, version }: Props = $props();

  type Segment = { kind: 'text'; text: string } | { kind: 'link'; url: string; text: string };

  const linkRe = /(@?https:\/\/github\.com\/[\w-]+\/[\w-]+\/commit\/([a-f0-9]{7,40}))|([^&])(#[0-9]+)/gim;

  function toSegments(summary: string): Segment[] {
    const trimmed = summary.replace(/[\r\n]+$/g, '');
    const segs: Segment[] = [];
    let last = 0;
    let m: RegExpExecArray | null;

    while ((m = linkRe.exec(trimmed)) !== null) {
      if (m.index > last) segs.push({ kind: 'text', text: trimmed.slice(last, m.index) });

      if (m[2]) {
        const url = m[1].replace(/^@/, '');
        const shortHash = m[2].slice(0, 7);
        segs.push({ kind: 'link', url, text: shortHash });
      } else if (m[4]) {
        segs.push({ kind: 'text', text: m[3] });
        const n = m[4].slice(1);
        segs.push({
          kind: 'link',
          url: `https://github.com/PaperMC/${project}/issues/${n}`,
          text: `#${n}`,
        });
      }
      last = linkRe.lastIndex;
    }
    if (last < trimmed.length) segs.push({ kind: 'text', text: trimmed.slice(last) });
    return segs;
  }

  type Row = { sha: string; fullMessage?: string; segments: Segment[] };
  let rows = $derived(
    build?.commits.map<Row>((c) => {
      const [firstLine, ...rest] = c.message.split(/\r?\n/);
      return {
        sha: c.sha,
        fullMessage: rest.length > 0 ? c.message : undefined,
        segments: toSegments(firstLine),
      };
    }) ?? []
  );
</script>

{#if rows.length > 0}
  {#each rows as row (row.sha)}
    <p class="commitMessage overflow-hidden break-words" style="word-wrap: break-word; hyphens: auto;">
      <a
        class="mr-1 font-mono text-blue-600 dark:text-blue-500"
        href={`${getProjectRepository(project, version)}/commit/${row.sha}`}
        target="_blank"
        rel="noreferrer"
      >
        {row.sha.slice(0, 7)}
      </a>

      <span title={row.fullMessage}>
        {#each row.segments as seg, i (i)}
          {#if seg.kind === 'text'}
            {seg.text}
          {:else}
            <a class="text-blue-600 dark:text-blue-500" href={seg.url} target="_blank" rel="noreferrer">{seg.text}</a>
          {/if}
        {/each}
      </span>
    </p>
  {/each}
{:else}
  <i class="text-gray-600">No changes</i>
{/if}
