// src/components/input/SoftwareDownloadButton.tsx
import { Menu, Transition } from "@headlessui/react";
import { Fragment, useContext, useState } from "react";

import ChevronDownIcon from "@/assets/icons/heroicons/chevron-down.svg";
import DocumentDownloadIcon from "@/assets/icons/heroicons/document-download.svg";
import Skeleton from "@/components/data/Skeleton";
import { DownloadsContext } from "@/lib/context/downloads";
import { getVersionBuildDownloadURL } from "@/lib/service/v2";

const SoftwareDownloadButton = () => {
  const { projectId, project, builds } = useContext(DownloadsContext);

  const latestBuild = builds && builds[builds.length - 1];
  const [copied, setCopied] = useState("");

  return (
    <Menu as="div" className="relative w-full">
      <div className="rounded-lg flex flex-row w-full md:w-100 bg-blue-600 transition-shadow text-white transition-color hover:shadow-lg">
        <a
          className="flex flex-row flex-1 items-center gap-8 pl-5 py-3"
          href={
            project &&
            latestBuild &&
            getVersionBuildDownloadURL(
              projectId,
              project.latestVersion,
              latestBuild.build,
              latestBuild.downloads["application"].name
            )
          }
          rel="noreferrer"
          target="_blank"
        >
          <div className="w-8 h-8">
            <DocumentDownloadIcon />
          </div>
          <div className="text-left flex-1 border-r border-gray-300/50">
            {project && builds && latestBuild ? (
              <>
                <span className="font-medium text-lg">
                  {project.name} {project.latestVersion}
                </span>
                <p className="text-gray-100">
                  {latestBuild && `Build #${latestBuild.build}`}
                </p>
              </>
            ) : (
              <>
                <Skeleton className="w-40 mb-2" />
                <Skeleton className="w-20 h-5" />
              </>
            )}
          </div>
        </a>
        <Menu.Button aria-label="Other download variants">
          <ChevronDownIcon className="w-6 h-6 text-gray-200 mx-5" />
        </Menu.Button>
      </div>
      <Transition
        as={Fragment}
        enter="transition ease-out duration-100"
        enterFrom="transform opacity-0 scale-95"
        enterTo="transform opacity-100 scale-100"
        leave="transition ease-in duration-75"
        leaveFrom="transform opacity-100 scale-100"
        leaveTo="transform opacity-0 scale-95"
      >
        <Menu.Items className="absolute left-0 mt-2 origin-top-left rounded-md bg-background-light-10 shadow-lg divide-y divide-gray-200 border border-gray-200 w-full md:w-auto dark:(bg-background-dark-80 divide-gray-800 border-gray-800)">
          {latestBuild &&
            Object.entries(latestBuild.downloads).map(([name, download]) => (
              <Menu.Item key={name}>
                {() => (
                  <div className="hover:bg-blue-100 dark:hover:bg-gray-800 transition-colors">
                    <a
                      href={
                        project &&
                        latestBuild &&
                        getVersionBuildDownloadURL(
                          projectId,
                          project.latestVersion,
                          latestBuild.build,
                          download.name
                        )
                      }
                      rel="noreferrer"
                      target="_blank"
                    >
                      <div className="px-4 py-3">
                        <div className="font-medium">
                          {download.name}
                          {name === "application" && (
                            <span className="ml-2 text-xs rounded-full py-0.5 px-2 bg-yellow-200/80 text-yellow-800">
                              Recommended
                            </span>
                          )}
                          {copied === download.sha256 && (
                            <span className="ml-2 text-xs rounded-full py-0.5 px-2 bg-green-200/80 text-green-800 transition ease-in-out duration-1000">
                              Copied
                            </span>
                          )}
                        </div>
                        <div className="text-gray-700 dark:text-gray-300 text-xs mt-1 truncate">
                          {download.sha256}
                          <span className={"justify-right ml-1 cursor-pointer"}>
                            <button
                              className="bg-gray-200 dark:bg-gray-800 rounded-full"
                              onClick={(evt) => {
                                evt.preventDefault();
                                navigator.clipboard.writeText(download.sha256);
                                setCopied(download.sha256);
                                setTimeout(() => setCopied(""), 2000);
                              }}
                            >
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                className="h-4 w-4"
                                viewBox="0 0 512 512"
                                fill="#fefefe"
                              >
                                <path
                                  fillRule="evenodd"
                                  d="M464 0H144c-26.51 0-48 21.49-48 48v48H48c-26.51 0-48 21.49-48 48v320c0 26.51 21.49 48 48 48h320c26.51 0 48-21.49 48-48v-48h48c26.51 0 48-21.49 48-48V48c0-26.51-21.49-48-48-48zM362 464H54a6 6 0 0 1-6-6V150a6 6 0 0 1 6-6h42v224c0 26.51 21.49 48 48 48h224v42a6 6 0 0 1-6 6zm96-96H150a6 6 0 0 1-6-6V54a6 6 0 0 1 6-6h308a6 6 0 0 1 6 6v308a6 6 0 0 1-6 6z"
                                  clipRule="evenodd"
                                />
                              </svg>
                            </button>
                          </span>
                        </div>
                      </div>
                    </a>
                  </div>
                )}
              </Menu.Item>
            ))}
        </Menu.Items>
      </Transition>
    </Menu>
  );
};

export default SoftwareDownloadButton;

// src/components/data/SoftwareDownloadButton.svelte
<script lang="ts">
  import { type Build, type ProjectDescriptor } from "@/utils/types";
  import { onMount } from "svelte";

  interface Props {
    projectId: string;
    project: ProjectDescriptor | undefined;
    build: Build | undefined;
    version: string;
    compact?: boolean;
    eol?: boolean;
    disabled?: boolean;
  }

  let { projectId, project, build, version, compact = false, eol = false, disabled = false }: Props = $props();

  let open = $state(false);
  let rootEl: HTMLDivElement | null = $state(null);
  let copied: Record<string, boolean> = $state({});

  function close() {
    open = false;
  }
  function toggle() {
    if (!disabled) open = !open;
  }
  function onDocumentClick(ev: MouseEvent) {
    const t = ev.target as HTMLElement | null;
    if (!rootEl) return;
    if (t && rootEl.contains(t)) return;
    close();
  }
  onMount(() => {
    document.addEventListener("click", onDocumentClick);
    return () => document.removeEventListener("click", onDocumentClick);
  });

  type DownloadEntry = [string, { name: string; checksums: { sha256: string }; size: number; url: string }];
  let downloadEntries = $derived(build ? (Object.entries(build.downloads) as DownloadEntry[]) : []);

  async function copySha256(evt: MouseEvent, entry: DownloadEntry) {
    evt.preventDefault();
    evt.stopPropagation();
    const [, d] = entry;
    if (!d.checksums.sha256) return;
    try {
      await navigator.clipboard.writeText(d.checksums.sha256);
      copied[d.name] = true;
      copied = { ...copied };
      setTimeout(() => {
        copied[d.name] = false;
        copied = { ...copied };
      }, 2000);
    } catch (error) {
      console.error("Failed to copy SHA256 checksum to clipboard:", error);
    }
  }
</script>

<div class="relative flex w-full flex-row md:w-100" bind:this={rootEl}>
  <div
    class={`btn transition-color flex flex-row rounded-md
      ${!compact ? "w-full md:w-100" : ""}
      ${eol ? "btn-eol" : `btn-${build?.channel?.toLowerCase()}`}
      ${disabled ? "cursor-not-allowed opacity-60" : ""}`}
  >
    <a
      class={`flex flex-1 flex-row items-center ${compact ? "gap-2 py-1 pl-2 leading-0" : "gap-8 py-3 pl-5"}`}
      href={build?.downloads["server:default"]?.url}
      target="_blank"
      aria-disabled={disabled}
      onclick={(e) => disabled && (e.preventDefault(), e.stopPropagation())}
    >
      <div class={compact ? "h-4 w-4" : "h-8 w-8"}>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
          />
        </svg>
      </div>

      <div class="flex-1 pr-2 text-left">
        {#if compact}
          <span class="text-sm font-medium">Download</span>
        {:else if projectId && build}
          <span class="text-lg font-medium">
            {project?.name ?? projectId}
            {version}
          </span>
          <p class="text-gray-{build?.channel == 'BETA' ? '600' : '100'}">{build ? `Build #${build.id}` : ""}</p>
        {:else}
          <div class="mb-2 h-6 w-40 animate-pulse rounded bg-gray-200/40 dark:bg-gray-700/40"></div>
          <div class="h-5 w-20 animate-pulse rounded bg-gray-200/30 dark:bg-gray-700/30"></div>
        {/if}
      </div>
    </a>

    <button
      class="grid h-auto w-8 shrink-0 cursor-pointer
             place-items-center rounded-r-lg border-l border-white/20
             leading-0 hover:bg-white/10 md:w-16
             dark:border-white/15"
      aria-haspopup="menu"
      aria-expanded={open}
      onclick={toggle}
      disabled={disabled || !build}
      title="More downloads"
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class={`text-gray-${build?.channel == "BETA" ? "600" : "100"} ${compact ? "h-4 w-4" : "h-5 w-5"}`}
        viewBox="0 0 20 20"
        fill="currentColor"
      >
        <path
          fill-rule="evenodd"
          d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
          clip-rule="evenodd"
        />
      </svg>
      <span class="sr-only">Toggle downloads menu</span>
    </button>

    <div
      class={`bg-background-light-10 dark:bg-background-dark-80 absolute z-40 mt-2 divide-y divide-gray-200 rounded-md border border-gray-200 shadow-md dark:divide-gray-800 dark:border-gray-800
              ${compact ? "right-0 origin-top-right" : "left-0 w-full origin-top-left md:w-auto"}
              ${open ? "block opacity-100" : "hidden opacity-0"}`}
      role="menu"
    >
      {#if build}
        {#each downloadEntries as entry (entry[1].name)}
          <a
            class="block transition-colors hover:bg-blue-100 dark:hover:bg-gray-800"
            href={entry[1].url}
            target="_blank"
            role="menuitem"
            onclick={() => (open = false)}
          >
            <div class="px-4 py-3">
              <div class="flex flex-wrap items-center gap-2 font-medium">
                <span class="text-gray-700 dark:text-gray-300">{entry[1].name}</span>
                {#if entry[0] === "application"}
                  <span class="rounded-full bg-yellow-200/80 px-2 py-0.5 text-xs text-yellow-800">Recommended</span>
                {/if}
                {#if copied[entry[1].name]}
                  <span class="rounded-full bg-green-200/80 px-2 py-0.5 text-xs text-green-800">Copied SHA256 checksum</span>
                {/if}
              </div>

              <div class="mt-1 inline-flex w-full items-center text-xs text-gray-700 dark:text-gray-300">
                <span class="truncate">{entry[1].checksums.sha256}</span>
                <button
                  class="ml-2 inline-flex size-6 items-center justify-center rounded hover:bg-black/5 dark:hover:bg-white/5"
                  onclick={(e) => copySha256(e, entry)}
                  title="Copy SHA256 checksum"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 512 512" class="size-4">
                    <path
                      d="M64 464H288c8.8 0 16-7.2 16-16V384h48v64c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V224c0-35.3 28.7-64 64-64h64v48H64c-8.8 0-16 7.2-16 16V448c0 8.8 7.2 16 16 16zM224 304H448c8.8 0 16-7.2 16-16V64c0-8.8-7.2-16-16-16H224c-8.8 0-16 7.2-16 16V288c0 8.8 7.2 16 16 16zm-64-16V64c0-35.3 28.7-64 64-64H448c35.3 0 64 28.7 64 64V288c0 35.3-28.7 64-64 64H224c-35.3 0-64-28.7-64-64z"
                    />
                  </svg>
                </button>
              </div>
            </div>
          </a>
        {/each}
      {/if}
    </div>
  </div>
</div>

<style>
  .size-4 {
    width: 1rem;
    height: 1rem;
  }
  .size-6 {
    width: 1.5rem;
    height: 1.5rem;
  }
  .size-8 {
    width: 2rem;
    height: 2rem;
  }

  [role="menu"] {
    top: 100%;
    transition: opacity 0.25s ease;
  }
</style>
