// src/components/Terminal.svelte
<script lang="ts">
  import { formatISOFullTime } from "@/utils/time";
  import { onMount } from "svelte";

  const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
  const getNaturalDelay = () => Math.floor(Math.random() * 80) + 40;

  let cmd = $state("");
  let args = $state("");
  let loading = $state("");
  let lines = $state<string[]>([]);
  let success = $state<string | null>(null);
  let history = $state<{ kind: "cmd" | "info"; text: string }[]>([]);

  let latestStableVersion = $state<string>("1.21.8");

  onMount(async () => {
    const response = await fetch("/internal-api/terminal");
    const data: { version: string } = await response.json();
    latestStableVersion = data.version;
  });

  function handleCommand(e: KeyboardEvent & { currentTarget: HTMLInputElement }) {
    if (e.key !== "Enter") return;

    const value = e.currentTarget.value.trim();
    let response: string;

    switch (value) {
      case "help":
        response = "Existing commands: help, downloads, plugins, docs, forums, team, contribute";
        break;
      case "downloads":
        window.location.href = "/downloads";
        response = "Redirecting...";
        break;
      case "plugins":
        window.location.href = "https://hangar.papermc.io";
        response = "Redirecting...";
        break;
      case "docs":
        window.location.href = "https://docs.papermc.io";
        response = "Redirecting...";
        break;
      case "forums":
        window.location.href = "https://forums.papermc.io";
        response = "Redirecting...";
        break;
      case "team":
        window.location.href = "/team";
        response = "Redirecting...";
        break;
      case "contribute":
        window.location.href = "/contribute";
        response = "Redirecting...";
        break;
      default:
        response = 'Unknown command. Type "help" for help.';
    }

    history = [...history, { kind: "cmd", text: value }, { kind: "info", text: response }];
    e.currentTarget.value = "";
  }

  $effect(() => {
    cmd = "";
    args = "";
    loading = "";
    lines = [];
    success = null;

    const outputLines = [
      `Starting minecraft server version ${latestStableVersion}`,
      'Preparing level "world"',
      "Preparing start region for dimension minecraft:overworld",
      "Time elapsed: 363 ms",
      "Preparing start region for dimension minecraft:the_nether",
      "Time elapsed: 147 ms",
      "Preparing start region for dimension minecraft:the_end",
      "Time elapsed: 366 ms",
      "Running delayed init tasks",
    ];

    let cancelled = false;

    (async () => {
      let currentCmd = "";
      for (const ch of "java") {
        if (cancelled) return;
        currentCmd += ch;
        cmd = currentCmd;
        await sleep(getNaturalDelay());
      }

      let currentArgs = "";
      for (const ch of " -jar paper.jar") {
        if (cancelled) return;
        currentArgs += ch;
        args = currentArgs;
        await sleep(getNaturalDelay());
      }

      for (let i = 0; i < 3; i++) {
        if (cancelled) return;
        loading = "Loading libraries, please wait" + ".".repeat(i + 1);
        await sleep(500);
      }

      for (const line of outputLines) {
        if (cancelled) return;
        lines = [...lines, line];
        await sleep(getNaturalDelay());
      }

      success = 'Done (2.274s)! For help, type "help"';
    })();

    return () => (cancelled = true);
  });
</script>

{#snippet InfoLog(children: string)}
  <div>
    <span class="text-amber-400">[{formatISOFullTime(new Date())} INFO]</span>: {children}
  </div>
{/snippet}

<div class="h-[1132px] max-h-[328px] w-[480px] rounded-lg bg-gray-800">
  <div class="flex w-full gap-2 rounded-t-lg bg-gray-900 p-2">
    <div class="h-2.5 w-2.5 rounded-full bg-red-500"></div>
    <div class="h-2.5 w-2.5 rounded-full bg-yellow-500"></div>
    <div class="h-2.5 w-2.5 rounded-full bg-green-500"></div>
  </div>

  <div class="flex max-h-[296px] flex-col-reverse overflow-y-hidden p-4 font-mono text-xs text-white">
    <div>
      {#if success}
        &gt;
        <input aria-label="terminal input" class="w-[420px] border-none bg-transparent focus:outline-none" onkeydown={handleCommand} />
      {/if}
    </div>

    <div>
      {#each history as item, index (index)}
        {#if item.kind === "cmd"}
          <div>&gt; {item.text}</div>
        {:else}
          {@render InfoLog(item.text)}
        {/if}
      {/each}
    </div>

    <div>
      {#if success}
        <div>
          <span class="text-amber-400">[{formatISOFullTime(new Date())} INFO]</span>: <span class="text-green-400">{success}</span>
        </div>
      {/if}
    </div>

    <div>
      {#each lines as line, index (index)}
        {@render InfoLog(line)}
      {/each}
    </div>

    <div>
      <span class="text-gray-400">{loading}</span>
    </div>

    <div>
      <span class="text-green-400">$ </span>
      <span class="text-blue-400">{cmd}</span>
      <span>{args}</span>
    </div>
  </div>
</div>

// src/components/data/Terminal.tsx
import type { KeyboardEvent } from "react";
import { type ReactNode, useEffect, useRef, useState } from "react";

import type { ProjectProps } from "@/lib/context/downloads";
import { formatISOFullTime } from "@/lib/util/time";

const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const getNaturalDelay = () => Math.floor(Math.random() * 80) + 40;

function InfoLog({ children }: { children: ReactNode }) {
  return (
    <div>
      <span className="text-amber-400">
        [{formatISOFullTime(new Date())} INFO]
      </span>
      : {children}
    </div>
  );
}

export function Terminal({ project }: ProjectProps) {
  const [cmd, setCmd] = useState("");
  const [args, setArgs] = useState("");
  const [loading, setLoading] = useState("");
  const [output, setOutput] = useState<ReactNode>(null);
  const [success, setSuccess] = useState<ReactNode>(null);
  const [input, setInput] = useState<ReactNode>(null);
  const [cmdOutput, _setCmdOutput] = useState<ReactNode>(null);

  const cmdOutputRef = useRef(cmdOutput);
  function setCmdOutput(data: ReactNode[]) {
    cmdOutputRef.current = data;
    _setCmdOutput(data);
  }

  const handleCommand = (event: KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "Enter") {
      let currentCmdOutput;
      switch (event.currentTarget.value) {
        case "help": {
          currentCmdOutput =
            "Existing commands: /help, /downloads, /plugins, /docs, /forums, /team, /contribute";
          break;
        }
        case "downloads": {
          window.location.href = "/downloads";
          currentCmdOutput = "Redirecting...";
          break;
        }
        case "plugins": {
          window.location.href = "https://hangar.papermc.io";
          currentCmdOutput = "Redirecting...";
          break;
        }
        case "docs": {
          window.location.href = "https://docs.papermc.io";
          currentCmdOutput = "Redirecting...";
          break;
        }
        case "forums": {
          window.location.href = "https://forums.papermc.io";
          currentCmdOutput = "Redirecting...";
          break;
        }
        case "team": {
          window.location.href = "/team";
          currentCmdOutput = "Redirecting...";
          break;
        }
        case "contribute": {
          window.location.href = "/contribute";
          currentCmdOutput = "Redirecting...";
          break;
        }
        default: {
          currentCmdOutput = "Unknown Command";
        }
      }
      setCmdOutput([
        cmdOutputRef.current,
        <div key={event.currentTarget.id}>
          {">"} {event.currentTarget.value}
        </div>,
        <InfoLog key={2}>{currentCmdOutput}</InfoLog>,
      ]);
      event.currentTarget.value = "";
    }
  };

  useEffect(() => {
    const outputLines = [
      `Starting minecraft server version ${project.latestStableVersion}`,
      'Preparing level "world"',
      "Preparing start region for dimension minecraft:overworld",
      "Time elapsed: 363 ms",
      "Preparing start region for dimension minecraft:the_nether",
      "Time elapsed: 147 ms",
      "Preparing start region for dimension minecraft:the_end",
      "Time elapsed: 366 ms",
      "Running delayed init tasks",
    ];

    (async () => {
      let currentCmd = "";
      for (const char of "java") {
        currentCmd += char;
        setCmd(currentCmd);
        await sleep(getNaturalDelay());
      }

      let currentArgs = "";
      for (const char of " -jar paper.jar") {
        currentArgs += char;
        setArgs(currentArgs);
        await sleep(getNaturalDelay());
      }

      for (let i = 0; i < 3; i++) {
        setLoading("Loading libraries, please wait" + ".".repeat(i + 1));
        await sleep(500);
      }

      let currentOutput: ReactNode[] = [];
      for (let i = 0; i < outputLines.length; i++) {
        currentOutput = [
          ...currentOutput,
          <InfoLog key={i}>{outputLines[i]}</InfoLog>,
        ];
        setOutput(currentOutput);

        await sleep(getNaturalDelay());
      }

      setSuccess(
        <InfoLog>
          <span className="text-green-400">
            Done (2.274s)! For help, type &quot;help&quot;
          </span>
        </InfoLog>,
      );

      setInput(
        <div>
          {">"}{" "}
          <input
            onKeyDown={(event) => handleCommand(event)}
            className="w-105 bg-transparent border-none outline-none"
          ></input>
        </div>,
      );
    })();
  }, [project.latestStableVersion]);

  return (
    <div className="max-h-82 w-120 h-283 rounded-lg bg-gray-800">
      <div className="w-full bg-gray-900 rounded-t-lg flex p-2 gap-2">
        <div className="w-2.5 h-2.5 bg-red-500 rounded-full" />
        <div className="w-2.5 h-2.5 bg-yellow-500 rounded-full" />
        <div className="w-2.5 h-2.5 bg-green-500 rounded-full" />
      </div>
      <div className="max-h-74 p-4 font-mono text-xs text-white overflow-y-hidden flex flex-col-reverse">
        {input}
        <div>{cmdOutput}</div>
        <div>{success}</div>
        <div>{output}</div>
        <div>
          <span className="text-gray-400">{loading}</span>
        </div>
        <div>
          <span className="text-green-400">$ </span>
          <span className="text-blue-400">{cmd}</span>
          <span>{args}</span>
        </div>
      </div>
    </div>
  );
}
